### PR TITLE
chore: remove some envs

### PR DESCRIPTION
**Pull request by kegechen**
deepin-wine will get scale factor from xft.dpi

### CODE REVIEW

**Review by zsien — APPROVED** [review]

**Review by zccrs — DISMISSED** [review]

**Comment by zsien** [comment]
这个把 https://github.com/linuxdeepin/dde-session/pull/75 的内容覆盖了

**Comment by kegechen** [comment]
https://github.com/linuxdeepin/dde-session/pull/80
@zsien

**Comment by kegechen** [comment]
see #80

**Pull request closed without merging**
